// music-player-vue/src/App.vue
<template>
  <div class="App">
    <h1>Music Player</h1>
    <audio controls>
      <source :src="files/test.mp3" type="audio/mpeg" />
      Your browser does not support the audio element.
    </audio>
  </div>
</template>

<script>
export default {
  name: 'App',
  computed: {
    audioUrl() {
      return '/play';
    },
  },
};
</script>

// music-player-react/src/App.js
import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <h1>Music Player</h1>
      <audio controls>
        <source src="/play" type="audio/mpeg" />
        Your browser does not support the audio element.
      </audio>
    </div>
  );
}

export default App;
